---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping
        image: aak1009/pingpong:latest
        ports:
        - containerPort: 9000
        resources:
         requests:
           memory: "64Mi"
           cpu: "125m"
         limits:
           memory: "128Mi"
           cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: ping
spec:
  type: LoadBalancer
  ports:
  - port: 9000
  selector:
    app: ping
